analytics: {}
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0
  lightness: 0.554054
  rhythmicContrast: 0
  saturation: 0.529279
cta: {}
layout_spectrum: 1
name: WhoIsAbishag
opengraph: {}
purpose: []
typography_spectrum: 0.8267032613512129
