analytics: {}
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.28591
  lightness: 0.553039
  rhythmicContrast: 0.424626
  saturation: 0.492612
cta: {}
layout_spectrum: 0.5997875640168786
name: WhoIsAbishag
opengraph: {}
purpose: []
typography_spectrum: 0.8267032613512129
