analytics: {}
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.608108
  lightness: 0.405405
  rhythmicContrast: 0.709459
  saturation: 0.317567
cta: {}
layout_spectrum: 1
name: WhoIsAbishag
opengraph: {}
purpose: []
typography_spectrum: 0.8267032613512129
